### PR TITLE
Update README.md to showcase the use of resources

### PR DESCRIPTION
**Pull request by tarunjain1st**

### CODE REVIEW

**Comment by pradyumnjain** [comment]
Hey, @tarunjain1st great work, just a few pointers change the content and for python and machine learning, go towards a more practical explanation. If possible also do mention a detailed learning path for beginners in the field of machine learning as creatively as you can. Also for your convenience, I have created a branch by your name, so make a PR on that it will be merged to master later.

**Comment by aniketbiprojit** [comment]
This was a good PR. Much cleaner than the tree I pushed to the README.

**Review by aniketbiprojit — COMMENTED** [review]
Links are in working condition.

**Comment by tarunjain1st** [comment]
what else do i need to add in this

**Comment by tarunjain1st** [comment]
and do i aslo need to make new PR for the updated readme

**Comment by pradyumnjain** [comment]
yeah just make a new PR with changes. @tarunjain1st  Make sure you the PR is to your designated branch. Will merge it with the Master branch then.

**Pull request closed without merging**
