### PR TITLE
fix: readme

### LINKED ISSUE #16: The current readme has bugs
The merge of #14 introduced un-formatted content to README

### PR DESCRIPTION
**Pull request by aniketbiprojit**
Updates #1 but does not close it.

Closes #16

### CODE REVIEW

**Comment by aniketbiprojit** [comment]
Force pushed to squash the commits.

**Review by aniketbiprojit — COMMENTED** [review]
Now renders fine

**Comment by pradyumnjain** [comment]
@aniketbiprojit  great!

**Comment by aniketbiprojit** [comment]
Add label hacktoberfest-accepted to the PR please.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by aniketbiprojit** [comment]
@pradyumnjain

**Pull request merged**
